### ISSUE TITLE
Error when importing the feed with postgresql

### ISSUE THREAD

**Issue by facundoolano** [mojotech/EPFImporter#1]
I'm trying to import the feed to a postgresql database, and it seems to work OK for some of the tables, but for others it throws this kinds of error:

2012-02-01 16:17:57,164 [ERROR]: Fatal error encountered while ingesting 'XXX/itunes20111026/application'
Traceback (most recent call last):
  File "XXX/EPFImporter/EPFIngester.py", line 137, in ingestFull
    self._populateTable(self.tmpTableName, skipKeyViolators=skipKeyViolators)
  File "XXX/EPFImporter/EPFIngester.py", line 422, in _populateTable
    cur.execute(exStr)
ProgrammingError: column "enull" does not exist at character 597

2012-02-01 16:17:57,165 [ERROR]: Last record ingested before failure: -1

Any idea why this might happen? Has this importer been tested to work with postgresql?

**Comment by TGOlson** [comment]
Any resolution with this one? I'm trying to use the Apple Epf importer with Postgres, and getting similar errors.

**Comment by SigniOS** [comment]
Zsign technical support:
Apple signature tool iPA supporting ios15 and ios16
Support the removal of dylib dynamic library
Support Windows Mobile mac
It can help solve the problems that IOS cannot be installed and verified
https://urlzs.com/44zCx
