### ISSUE TITLE
Suddenly error with decoding unicode not supported

### ISSUE THREAD

**Issue by Behinder** [mojotech/EPFImporter#7]
Code worked fine for 2 years now it is not:

```
Traceback (most recent call last):
  File "EPFImporter.py", line 454, in <module>
    main()
  File "EPFImporter.py", line 437, in main
    fieldDelim=fieldSep)
  File "EPFImporter.py", line 222, in doImport
    ing.ingest(skipKeyViolators=skipKeyViolators)
  File "/Users/sebastian/Documents/test2/EPFIngester.py", line 111, in ingest
    self.ingestIncremental(skipKeyViolators=skipKeyViolators)
  File "/Users/sebastian/Documents/test2/EPFIngester.py", line 206, in ingestIncremental
    skipKeyViolators=skipKeyViolators)
  File "/Users/sebastian/Documents/test2/EPFIngester.py", line 375, in _populateTable
    colVals = unicode(", ".join(stringList), 'utf-8')
TypeError: decoding Unicode is not supported
```

**Comment by SigniOS** [comment]
Zsign technical support:
Apple signature tool iPA supporting ios15 and ios16
Support the removal of dylib dynamic library
Support Windows Mobile mac
It can help solve the problems that IOS cannot be installed and verified
https://urlzs.com/44zCx
